### ISSUE TITLE
How to develop UI Options Page?

### ISSUE THREAD

**Issue by kubek93** [VasilyShelkov/create-react-extension#17]
That is a great library for fast creates chrome extension. But there is one thing which confuses me a little bit. Maybe somebody of you have a smart idea to solve that.

Which approach is the best and how can I develop options page for the extension not having cra support?

**Comment by zoffyzhang** [comment]
there you go #16

**Comment by VasilyShelkov** [comment]
Hi, sorry I haven't been very active... If anyone is interested in adding an MR, please feel free.. I have been intending to add support to develop both an options page, new tab and developer tools bundle.

I will get look to add this feature in the coming couple of weeks so that people don't need to eject.

**Comment by kubek93** [comment]
Thanks for the response! When I come back to my work with plugin I will try create PR with changes.

**Comment by VasilyShelkov** [comment]
The latest [release](https://github.com/VasilyShelkov/create-react-extension/releases/tag/4.0.10) of create-react-extension now supports the options.html page.

For those wanting to update to support the new options page, just update `react-browser-extension-scripts` to version `4.0.10` and add the following files:
- `public/options.html`([see template example](https://github.com/VasilyShelkov/create-react-extension/blob/master/packages/cra-template/template/public/options.html))
- `src/options/index.js` ([see template example](https://github.com/VasilyShelkov/create-react-extension/blob/master/packages/cra-template/template/src/options/index.js))
- `src/options/Options.js` ([see template example](https://github.com/VasilyShelkov/create-react-extension/blob/master/packages/cra-template/template/src/options/Options.js))

This version might looks strange, I intend to follow the versions of react-scripts and add 0-9 for any specific `create-react-extension` features that are released
