### ISSUE TITLE
Is there anyway to build one more page like options?

### ISSUE THREAD

**Issue by dim0147** [VasilyShelkov/create-react-extension#25]
Hi, currently my extensions have a page called dashboard.html using react for render, I develop and build by changing the original options folder to options_default and create new folders named options but inside this folder is the dashboard site, so whenever I build or develop I need to change the name of the folder to options so it can work, is there any tips for easier than this way? thanks

**Comment by khlevon** [comment]
Hi, yes there is. You can run `yarn eject` command and then did your custom changes in weback config, including in the build process your custom HTML file. Then you can access it with this url.
`chrome-extension://<you_extension_id>/dashboard.html`

**Comment by dim0147** [comment]
Duplicate of #23  I have run `yarn eject` and get the same error as this issue, and it will be nice if can have a simple instruction on how to add a custom page like options as simple, I got confused to read the config of that files. Thanks

**Comment by khlevon** [comment]
To fix #23 issue copy [This folder](https://github.com/VasilyShelkov/create-react-extension/tree/master/packages/react-scripts/scripts/utils) into your `scripts` folder which you can find after ejecting. And about instruction, the simplest way is searching in your project `appOptionsHtml` and `appOptionsJs` phrases and duplicate them changing `options` to `dashboard`

**Comment by dim0147** [comment]
Thank you very much!!!
