### ISSUE TITLE
"chrome is not defined"

### ISSUE THREAD

**Issue by v5out** [VasilyShelkov/create-react-extension#29]
When I add any reference to chrome, e.g. "chrome.cookies.getAll(...", npm start displays the error, "chrome is not defined". How do I fix that?

For example, without making any modifications to the app as it is generated and then dropping the following code into the background/index.js file causes this error:

chrome.cookies.getAll({
    domain: ".youtube.com"
}, function (cookies) {
    for (var i = 0; i < cookies.length; i++) {
        console.log(cookies[i] + "deleted");
        chrome.cookies.remove({
            url: "https://" + cookies[i].domain + cookies[i].path,
            name: cookies[i].name
        });
    }
});

**Comment by donggiggedin** [comment]
`/*global chrome*/`

Add this row at the first line of the file

**Comment by v5out** [comment]
Thanks

**Comment by cokacode** [comment]
can you explain why this works, sorry I could not find anything related to this directive

**Comment by mehimanshupatil** [comment]
that's because linter tries to find the chrome definition which it's not able to find and we are telling linter that chrome is defined globally
refer this
https://eslint.org/docs/latest/rules/no-undef

**Comment by danieln-juno** [comment]
> `/*global chrome*/`
> 
> Add this row at the first line of the file

worked perfectly. thanks!

**Comment by lpe234** [comment]
`npm install @types/chrome --save-dev`
