### ISSUE TITLE
Is this app going to support v3

### ISSUE THREAD

**Issue by mehimanshupatil** [VasilyShelkov/create-react-extension#40]
@VasilyShelkov are you going to add support for v3.

**Comment by Danscap** [comment]
imo, this already does support V3. If you dig around some of the threads here, there's some manifest files that make this work with V3.

I'm already using this for V3 and it works. The only thing is you have to manually update the manifest file yourself.

**Comment by mehimanshupatil** [comment]
yes, I have also created an extension with this library and moved it to v3 successfully.

I mean to say upgrading template files, dependencies and fixing hot-reload for a service worker.

related to #37
