### ISSUE TITLE
Using typescript with CRA-chrome-extensions

### ISSUE THREAD

**Issue by KabakaWilliam** [VasilyShelkov/create-react-extension#42]
It's a bit unclear how to configure this fork of CRA with typescript. Is there any documentation or examples of how to set this up for chrome extensions? Also, really appreciate the work you're doing here!

**Comment by mehimanshupatil** [comment]
just run the script with template as browser-extension-typescript
```npx create-react-app my-browser-extension --scripts-version react-browser-extension-scripts --template browser-extension-typescript```
if you want to move existing project to typescript follow [CRA guide](https://create-react-app.dev/docs/adding-typescript/)

**Comment by KabakaWilliam** [comment]
Thanks for the help.
